---
- name: Install Jenkins
  hosts: local

  roles:
    - jenkins

  post_tasks:
    - name: Start Jenkins
      shell: "{{ jenkins_home }}/start.sh"

    - name: Wait for Jenkins to start
      pause:
        seconds: 10

    - name: Show success message
      debug:
        msg: "Jenkins running at http://localhost:{{ jenkins_port }}"
