---
- name: Restart Tomcat
  shell: |
    {{ tomcat_home }}/bin/shutdown.sh || true
    sleep 2
    export JAVA_HOME={{ java_home }}
    export CATALINA_HOME={{ tomcat_home }}
    export JENKINS_NODE_COOKIE=dontKillMe
    nohup {{ tomcat_home }}/bin/startup.sh > /dev/null 2>&1 &
    sleep 10
